Solid
Mohaymen-Academy/SE_Team02_Summer1402 pull request #1
Opened 2023-07-19 05:22 UTC by KimiaHosseini

review the code :)

2023-07-19 07:35 UTC, Ali-Athary commented
1. Normalization class is useless.
2. map.get(word).contains(fileName) is not optimized because check if exists in array list in O(n).
3. WordManipulation not used any where.

2023-07-21 07:45 UTC, Hossein-29 commented
1.QueryLists class isn't applying second principle of SOLID cause you may have others filters then you need to modify instead of adding.

2.FileReader class isn't applying fifth principle of SOLID cause you may need to read the file in a custom way in the future so an interface would be good solution to this.

2023-07-21 22:44 UTC, AmirHossein-Naqdali reviewed
- Different style guides in some parts of the code (e.g. ReadPrinciple lines 12, 17-18)
- Are Java doc comments used correctly? Weren't multi-line comments a better option?

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/Execute.java
> +            readPrinciple.setSplitMarks(query.substring(temp + 4));
- "temp" is not an appropriate name.
- if (temp != -1) is a better condition (more specifically that no such value exists).
- temp + 4 = splitMarksIndex (Increases readability).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/QueryLists.java
> +    private ArrayList<String> forbidden;
Fields can be final (not crucial but better for clean code?).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/IFileReader.java
> +public interface IFileReader {
IFileReader does not match with Java naming conventions (the same goes with INormalize _I believe Normalizer would be a better name).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/InvertedIndex.java
> +import java.util.ArrayList;
Unused import statement.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/InvertedIndex.java
> +    private ReadPrinciple readPrinciple;
readPrinciple can be final.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/InvertedIndex.java
> +            map.get(word).add(fileName);
```
if (!map.get(word).contains(fileName))
	map.get(word).add(fileName);
```

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/Main.java
> +        readPrinciple.normalization = new Stemmer();
Encapsulation for normalization field in readPrinciple class (accessed with setters and getters).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/ReadPrinciple.java
> +public class ReadPrinciple {
Class' name does not give a sense of what it is responsible for (to me at least).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/ReadPrinciple.java
> +        this.splitMarks = new ArrayList<>(Arrays.asList(splitMarks.split("")));
Since splitMarks is of ArrayList type, I think it is better to have adding/removing methods for it instead of setting method.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/ReadPrinciple.java
> +    public boolean splitBy(Character c){
splitBy is not a suitable name for a method with boolean output (isSplittableBy/isSplittedBy maybe?).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +public class SearchProcess {
SearchProcessor instead of SearchProcess?

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +    private QueryLists queryLists = new QueryLists();
- Fields can be final.
- queryLists better be initialized in the constructor.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +        queryLists.categorization(query.split(" "), readPrinciple);
Using the regex of white spaces (tab, multiple spaces, ...) instead of only a space makes the code work with other inputs.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +            flag = false;
The "flag" name does not show what the variable is responsible for.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +//        checkForced(true,queryLists.getEssential());
? (Is boolean input necessary?)

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/SearchProcess.java
> +        ans = new HashSet<>(fileReader.getFilesName());
If we want more than one search then for every search we read files names (Does "ans" need to be initialized at all?).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/Stemmer.java
> +class Stemmer implements INormalize {
- Hard to read and maintain from developing pov.
- The class is so long.
- Names of class fields are not good and do not show their responsibilities.
- Private methods don't need to be final.
- Lines 55 and 71 can be replaced with Java built-in functions (System.arraycopy()).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/TxtFileReader.java
> +    private String path;
"path" can be final.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/TxtFileReader.java
> +            word = "";
If-else statements can be used instead of continue (to increase readability).

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/TxtFileReader.java
> +                fileReader = new FileReader(path + fileName);
"fileReader" is only used in this method (and is "newed" every time), so seems it should be a local variable instead.

2023-07-21 22:44 UTC, AmirHossein-Naqdali commented on Phase1/src/ReadPrinciple.java
> +    private ArrayList<String> splitMarks;
Why not ArrayList of Characters?

2023-07-22 06:06 UTC, Kiasoh commented on Phase1/src/InvertedIndex.java
> +            map.get(word).add(fileName);
null ref is not handled in your case (word might not be in map)

2023-07-22 06:11 UTC, Kiasoh commented on Phase1/src/Main.java
> +        readPrinciple.normalization = new Stemmer();
your comment is valid but it contradicts S in SOLID. we used to have a separate class for handling normalization but due to Team03 comment and very small responsibility of that class , we got rid of the class and the setter had to be destroyed as well because no other class can have it (single responsibility).

2023-07-22 06:15 UTC, Kiasoh commented on Phase1/src/ReadPrinciple.java
> +        this.splitMarks = new ArrayList<>(Arrays.asList(splitMarks.split("")));
readPrinciple.setSplitMarks(" ");
user can set his splitmarks whenever he/she wants. adding/removing methods are simply extra and useless

2023-07-22 06:25 UTC, Kiasoh commented on Phase1/src/SearchProcess.java
> +public class SearchProcess {
Either Processor or SearchProcess.
we believe SearchProcess is more vivid.

2023-07-22 06:32 UTC, Kiasoh commented on Phase1/src/SearchProcess.java
> +//        checkForced(true,queryLists.getEssential());
yeah. long storyyyyyyyyyyyy. ask me in person :)

2023-07-22 06:41 UTC, Kiasoh commented on Phase1/src/SearchProcess.java
> +        ans = new HashSet<>(fileReader.getFilesName());
yep. maybe misplaced , but in order to remove duplicate code , it has to be in constructor.
When you run Execute.run , we create new map, read files again, and.... We believe that doing this , makes the user more comfortable. the program will be easier to understand and simpler to use.

2023-07-22 06:43 UTC, Kiasoh commented on Phase1/src/Stemmer.java
> +class Stemmer implements INormalize {
comment this review on the person who has wrote this Stemmer!
honestly im to lazy to edit his code and im with you to the very end brother.
his dumbass should do it!

2023-07-22 06:48 UTC, Kiasoh commented on Phase1/src/TxtFileReader.java
> +                fileReader = new FileReader(path + fileName);
it is "newed" everytime a document should be readed!
it's nescessary.

2023-07-22 06:49 UTC, Kiasoh commented on Phase1/src/ReadPrinciple.java
> +    private ArrayList<String> splitMarks;
no dif really. we set string in order to prevent future unnecessary complexity.

2023-07-22 07:32 UTC, HosseinGh82 requested changes
ریویو دوم توسط تیم 3 انجام شد.
کد شما بسیار خوانا بود👍👌

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/Boz/boz.txt
پوشه Boz را حذف کنید.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/Execute.java
یه تابع برای سرچ کردن و یک تابع برای setup کردن باشه بهتره برای اینکه بشه چند باز سرچ کرد بدون اینکه بخواهیم هر بار مپ را درست کنیم.
نکته اینتر: بین هر تابع باید یک خط خالی باشد و بعد از کلاس هم همینطور.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/IFileReader.java
برای نام گذاری های "interface" از 'I' استفاده نکنید.
فایل ریدر فقط باید از فایل کلمات را بخواند و محتوا را برگرداند نباید کار درست کردن مپ در این کلاس انجام شود. بر اساس اصل "تک مسئولیتی" کد تمیز.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/INormalize.java
نکته نام گذاری interface.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/InvertedIndex.java
نکته Enter.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/Main.java
نکته Enter.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/QueryLists.java
نکته Enter.
اگر از یک نرمالیزیشن استفاده شود که حروف فقط باقی بماند باعث میشود مثبت و منفی درست تشخیص داده نشود و همه کوئری ها به صورت essential تشخیص داده شوند.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/ReadPrinciple.java
نکته Enter.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/ReadPrinciple.java
> +    }
این قسمت باید از نرمالیزیشن استفاده شود به جای این کار.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/ReadPrinciple.java
> +    public boolean splitBy(Character c){
این اسم مناسب نیست برای کاکرد تابع، تغییر داده شود.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/ReadPrinciple.java
> +    }
این تابع باید بگوید که حروف الفبا است یا نه.
این تابع فقط روی حروف کوچک کار می کند.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/ReadPrinciple.java
> +    private ArrayList<String> splitMarks;
این جا بهتر است به جای رشته از کاراکتر استفاده شود.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/SearchProcess.java
اسم تابع و متغیر ans مناسب نیست بهتر است از result استفاده شود یا answer.
اسم تابع هایی که waste دارند خوب نیست نسبت به کارکرد تابع ها.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/SearchProcess.java
> +//        checkForced(true,queryLists.getEssential());
کد کامنت شده که استفاده نخواهد شد حذف شود.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/SearchProcess.java
> +    private void checkForced(boolean isEssential, ArrayList<String> query) {
اسم این تابع خوب نیست.
ورودی بولین که میگیرد به کار نمی آید چون فقط یکبار با false فراخوانی می شود.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/TxtFileReader.java
> +            if (in.getReadPrinciple().splitBy(c)) {
به جای split کردن دستی می توانید از تابع آماده خود جاوا استفاده کنید.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/WordManipulation.java
> +
اینجا enter اضافه وجود دارد.

2023-07-22 07:32 UTC, HosseinGh82 commented on Phase1/src/Main.java
> +        //use from console
اینجا کد استفاده نشده است.

2023-07-22 09:07 UTC, KimiaHosseini commented on Phase1/src/SearchProcess.java
> +//        checkForced(true,queryLists.getEssential());
دوتا الگوریتم برای پیدا کردن essential ها داریم که سرعت هایشان متفاوت است و میتوانیم از کد کامنت شده استفاده کنیم برای سرعت بیشتر در بعضی حالات

2023-07-22 09:11 UTC, KimiaHosseini commented on Phase1/src/SearchProcess.java
> +    private void checkForced(boolean isEssential, ArrayList<String> query) {
حالتی که با true فراخوانی میشود کامنت شده است( راه دیگر برای essential ها)
و چون هر دو کار مربوط به essential ها و forbidden ها را با false,true هندل میکند اسم آن را forced گذاشته ایم.

2023-07-22 10:48 UTC, KimiaHosseini commented on Phase1/src/Main.java
> +        //use from console
اگر بخواهیم از کنسول استفاده کنیم از کامنتی در میاریم

2023-07-22 11:19 UTC, HosseinGh82 approved these changes

2023-07-22 12:18 UTC, AmirHossein-Naqdali approved these changes
Good Luck :)

2023-07-29 08:37 UTC, closed without merging