Phase3
Mohaymen-Academy/SE_Team02_Summer1402 pull request #2
Opened 2023-07-25 11:09 UTC by KimiaHosseini

2023-07-25 12:56 UTC, HosseinGh82 requested changes
بهتر بود تعداد کلمات داکیومنت در جای مختلف ذخیره کنید.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Chainsaw.java
اسم این کلاس خوب نیست بهتره به edge n-gram تغییر کند.
از گتر استفاده نشده پاک کنید.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Chainsaw.java
> +import java.util.ArrayList;
نکته Enter: بهتر است بین این دو یک اینتر بزنید.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Document.java
نکته اینتر.
چرا هم AllArgsConstructor دارید هم noArgs.
نام کلاس مناسب نیست.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Document.java
> +    public static Document createNewDoc(String name , int numWords)
به جای این تابع میتوانید از لامباک استفاده کنید و کانستراکتور بزنید.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Document.java
> +//        });
کد استفاده نشده پاک شود.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/Execute.java
نکته اینتر.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/FileScanner.java
قانون single responsibilty رعایت نشده است هم فایل را می خواند و هم آن را به Inverted index تبدیل می کند.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/QueryLists.java
می توانید لامباک گتر استفاده کنید.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/ReadPrinciple.java
> +@Getter @AllArgsConstructor
چون به صورت بیلدر استفاده کردید دیگه @AllArgsConstructor نمی خواهد.

2023-07-25 12:56 UTC, HosseinGh82 commented on Phase1/src/main/java/TxtFileReader.java
> +
کد کامنت شده پاک شود

2023-07-25 13:51 UTC, KimiaHosseini commented on Phase1/src/main/java/Document.java
هردو مدل cunstructor را میخواهیم، برای ارث بری NullDocumentInfo

2023-07-26 10:10 UTC, HosseinGh82 approved these changes

2023-07-28 05:52 UTC, Soltaniant submitted a review, later dismissed
خداقوت و خسته نباشید.
فکر می‌کنم دچار overengineering شدیم. برای همین تست‌هامون هم خیلی سخت بودن و ماک شدن زیادی نیاز داشت.
این مفهوم که داریم یک لایبرری می‌زنیم و بقیه باید بتونن ازش استفاده کنن (حتی با کانفیگ‌های خودشون) باید در کنار این قرار بگیره که استفاده از لایبرری هم باید خیلی ساده و سرراست باشه.

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/books/Clean Architecture, A Craftsman's Guide to Software Structure and Design.txt
> +kiarash
:)

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/books/Code Complete.txt
> +Protecting yourself from "cruel world of incorrect data". Use assertions to scoreHolder assumptions made in the code.
:)

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/boz2/file.txt
> +kimia
این فایلای تستی و موقتمون رو حداقل توی یه folder مناسب نگه داریم دیگه :)

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/boz2/zf.txt
> +boz1
اینم همین‌طور

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/pom.xml
> +        </dependency>
تکراری

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Chainsaw.java
> +    public List<String> nGram(String word){
style: `){` -> `) {`

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Chainsaw.java
> +        for (int i = min; i <=max ; i++) {
style: `<=max` -> `<= max`

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Document.java
> +
فاصله نباشد بین import های عادی
نکته: بین ایموپورت‌های عادی با staticها فاصله میذارن معمولا

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Execute.java
> +    public Execute(ArrayList<Guard> guards ,ArrayList<FileScanner> fileReaders) throws Exception {
فاصله بین متود و فیلد
فاصله بین دو تا متود
(یک خط فاصله داشته باشیم)
```java
    private final ArrayList<Guard> guards;

    private boolean CheckRunable() {
        return fileReaders.isEmpty() || guards.isEmpty();
    }

    public Execute(ArrayList<Guard> guards ,ArrayList<FileScanner> fileReaders) throws Exception {
```

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Execute.java
> +                return 0;
فکر کنم خود منها کردن این دو امتیاز از هم کفایت می‌کرد:
```java
return o1.getScore() - o2.getScore()
```

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Execute.java
> +            return query;
متوجه عملکرد این تابع نشدم. اگر کارش trim کردن یه متنه، خود string چنین تابعی رو داره.

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/GateKeeper.java
> +
فاصله

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/GateKeeper.java
> +public class GateKeeper implements Guard {
دو تا اسم GateKeeper و Gaurd رو اصلا درک نکردم :|

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/InvertedIndex.java
> +    public InvertedIndex() {
فاصله

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Main.java
> +    }
کد کامنت شده نداشته باشیم

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Normalizable.java
> +public interface Normalizable {
فکر نمی‌کنم `normalizable` اسم مناسبی باشه.

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/Normalizable.java
> +    }
دقیقا `super()` داره کدوم کانستراکتور رو کال می‌کنه. اصلا نیازی هست؟

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/ScoreHolder.java
> +    }
این مکانیزم برای مرتب‌سازی، بیش از حد زمان‌بر نیست؟ کلی هم داریم اینستنس ScoreHolder تولید می‌کنیم.

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/ReadPrinciple.java
> +public class ReadPrinciple {
در خط‌های جداگانه باشن

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +        }
بدون `{}`

```java
 if (query.isEmpty())
            return;
 
```

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +        }
همینطور: `{}`
```java
        else result = new HashSet<>();
```

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +//                    iterator.remove();
// commented out

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +//        it.forEachRemaining(doc -> {
// commented out

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +//        });
commen

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/SearchProcess.java
> +//        checkForced(true,queryLists.getEssential());
comment

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/TxtFileReader.java
> +    private final Guard guard;
وابستیگیش به Gaurd منطقی نیست.

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/main/java/TxtFileReader.java
> + */
این کامنت اگر درست باشه که خیلی بده :|
اگر درست نباشه هم نکته همینه! وقتی از کامنت‌ استفاده می‌شه، یکی از مشکلات اینه که شما کد رو آپدیت می‌کنی ولی یادت میره کامنت‌ها رو هم آپدیت کنی

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/test/java/ExecuteTest.java
> +////    public void haha() {
comment

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/test/java/GateKeeperTest.java
> +import java.util.ArrayList;
فاصله

2023-07-28 05:52 UTC, Soltaniant commented on Phase1/src/test/java/InvertedIndexTest.java
> +    }
:|

2023-07-28 10:40 UTC, KimiaHosseini commented on Phase1/src/main/java/Execute.java
> +            return query;
از این تابع برای حالتی که بخواهیم کوئری ها رو از کنسول بگیریم استفاده میکنیم به این صورت که کاربر رشته ای که میخواهد سرچ کنه رو مینویسه و بعد برای مشخص کردن split mark ها یه /sm مینویسه و جلوی اون split markهایی که میخواد.
مثلا      word1 +word2 -word3 /sm //r//n//s,a
این تابع split mark ها را جدا میکنه و به readprinciple میدهد و query را جدا میکند و return میکنه

2023-07-28 13:20 UTC, KimiaHosseini commented on Phase1/src/main/java/Main.java
> +    }
اگر بخواهیم داخل کد کوئری و split mark ها را مشخص کنیم از قسمت کامنت نشده زیر کامنت `use from code` استفاده میکنیم، اگر با کنسول این بخش ( زیر کامنت `use from console` ) را از کامنتی در میاریم

2023-07-29 06:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Chainsaw.java
> +        }
Redundant brackets.

2023-07-29 07:43 UTC, Kiasoh commented on Phase1/src/main/java/TxtFileReader.java
> +    private final Guard guard;
قسمتی از اون overengineering هست که گفتین.
برنامه یک فرم پیچیده داره که باعث میشه بتونی از جاهای مختلف(فایل اسکنر) با قوانین مختلف (گارد) کلمه ها رو استخراح کنن و بعد به مپ اضافه کنن.
اینکه با کدوم قانون قراره بخونه (کدوم نگهبان رو داشته باشه) رو میتونه تعیین کنه. توی استفاده ساده و  مشخصا نیازی نیست هر کدوم یک گارد مخصوص داشته باشن اما برای کاستومایز بودن بیشتر این آینده-لایبری( :) ) نکته مثبت حساب میشه
این آپشن وجود داره که دامی پروف بشه اما غیر از اون وابستگی اش با توجه به ساختار برنامه، منطقیه

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Document.java
> + */
A blank line is needed.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
What is the purpose of this class? Can't ReadPrinciple be a field in InvertedIndex?

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(String word, Document document) {
Why public?

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(List<String> words, Document document) {
Why public?

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/InvertedIndex.java
> +    private HashMap<String, Set<ScoreHolder>> map;
Field can be final.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Main.java
> +import java.util.Scanner;
Unused import statement.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/ScoreHolder.java
> +        }
Redundant brackets.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ChainsawTest.java
Can have `ngramMaxSmallerThanWordLength()` test.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
We should check the list size.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
We should check the list size.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
We should check the list size.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ScoreHolderTest.java
> +
Redundant blank line.

2023-07-29 08:32 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +    @BeforeEach
A blank line is needed.

2023-07-29 08:37 UTC, closed without merging