Phase4
Mohaymen-Academy/SE_Team02_Summer1402 pull request #3
Opened 2023-07-29 07:45 UTC by Kiasoh

2023-07-29 09:17 UTC, AmirHossein-Naqdali requested changes
- Well done!
- You can package classes in java folder.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Document.java
> +    public static ArrayList<Document> documents = new ArrayList<>();
Why public?

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Chainsaw.java
> +public class Chainsaw {
The class name is not appropriate.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Document.java
> +/**
A blank line is needed.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Execute.java
> +import lombok.NoArgsConstructor;
Unused import statement.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Execute.java
> +    }
- Move comments for `CheckRunnable()`.
- `CheckRunnable()` name is not camelCase.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Execute.java
> +    /**
A blank line is needed.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Guard.java
The name doesn't give a sense of what it is responsible for.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
- Why not have `ReadPrinciple` as a field in `InvertedIndex` and get rid of this class?
- The name doesn't give a sense of what it is responsible for.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(String word, Document document) {
Why public?

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(List<String> words, Document document) {
Why public?

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/InvertedIndex.java
> +    private HashMap<String, Set<ScoreHolder>> map;
Field can be final.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/Main.java
> +import java.util.Scanner;
Unused import statement.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/main/java/ScoreHolder.java
> +        }
Redundant brackets.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ChainsawTest.java
Can have `ngramMaxSmallerThanWordLength()` test.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +    @BeforeEach
A blank line is needed.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +    {
Blank line and style format.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +                return false;
```Java
            if (ScoreHolder.contains(ha, doc).getClass() == NullScoreHolder.class)
                return false;
```

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +    {
Blank line and style format.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        }
Redundant brackets.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +
- 65: A blank line is needed.
- 67: Redundant blank line.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var expectedResult = new ArrayList<ScoreHolder>();
Using `var` is not a good practice.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("kimia")) ;
Using `var` is not a good practice.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("+kimia")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("-boz1boz1")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("asd +kimia")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("-boz1boz1 +boz1")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("-boz1boz1 boz1")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +        var actualResult =new ArrayList<>(execute.run("kimia +boz1 -boz1boz1")) ;
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ExecuteTest.java
> +}
Redundant blank lines.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
Should check the list's size.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/QueryListsTest.java
> +    }
Same.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/ScoreHolderTest.java
> +
Redundant blank line.

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/SearchProcessTest.java
> +                return false;
```Java
            if (ScoreHolder.contains(ha, doc).getClass() == NullScoreHolder.class)
                return false;
```

2023-07-29 09:17 UTC, AmirHossein-Naqdali commented on Phase1/src/test/java/SearchProcessTest.java
> +
Redundant blank line.

2023-07-29 09:38 UTC, Kiasoh commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(String word, Document document) {
if someone uses his own class for reading files , he may want to add to the map by one word rather than an array

2023-07-29 09:38 UTC, Kiasoh commented on Phase1/src/main/java/Guard.java
it guards the map :)

2023-07-29 09:40 UTC, Kiasoh commented on Phase1/src/main/java/GateKeeper.java
1- the funny thing is, THE VERY FUNNY THING IS that the program was ok before some dumbass reviews. but overall , the program has changed greatly and every filereader can have his own GateKeeper(Guard) which has the readprinciple in it.
2 - it is a guard that protects the gate (to map) :)))))))))))))))))

2023-07-29 09:41 UTC, Kiasoh commented on Phase1/src/main/java/GateKeeper.java
> +    public void addToMap(List<String> words, Document document) {
'cause fileReader uses it

2023-07-29 09:43 UTC, Kiasoh commented on Phase1/src/main/java/Main.java
> +import java.util.Scanner;
it is used. just commented :)

2023-07-29 09:48 UTC, Kiasoh commented on Phase1/src/test/java/ExecuteTest.java
> +        var expectedResult = new ArrayList<ScoreHolder>();
agreed. but it is what it is :))))))))))))))))))))))))))))))))

2023-07-29 13:38 UTC, KimiaHosseini commented on Phase1/src/main/java/Document.java
> +    public static ArrayList<Document> documents = new ArrayList<>();
چون استاتیک است و نیاز به گرفتن آن از روی کلاس داریم و گذاشتن گتر و ستر استاتیک منطقی نبود

2023-07-29 13:41 UTC, KimiaHosseini commented on Phase1/src/test/java/ChainsawTest.java
it is same with ngramNormalWordLength()

2023-07-30 05:48 UTC, AmirHossein-Naqdali approved these changes

2023-07-30 05:56 UTC, closed without merging